/**
 * Ödeme periyodu — bir firmanın hangi sıklıkta faturalandırılacağı.
 *
 * Bir fatura "Ödendi" yapıldığında sonraki dönemin faturası bu kurallara göre
 * otomatik açılır. Hesap tek yerde tutulur ki API, panel ve ileride eklenecek
 * ekranlar aynı sonucu üretsin.
 */

export type BillingPeriod =
  | "HAFTALIK"
  | "IKI_HAFTALIK"
  | "AYLIK"
  | "IKI_AYLIK"
  | "OZEL_GUN"
  | "MANUEL";

export const BILLING_PERIODS: BillingPeriod[] = [
  "HAFTALIK",
  "IKI_HAFTALIK",
  "AYLIK",
  "IKI_AYLIK",
  "OZEL_GUN",
  "MANUEL",
];

export const BILLING_PERIOD_LABEL: Record<BillingPeriod, string> = {
  HAFTALIK: "Her hafta",
  IKI_HAFTALIK: "İki haftada bir",
  AYLIK: "Her ay",
  IKI_AYLIK: "İki ayda bir",
  OZEL_GUN: "Özel — belirli gün aralığı",
  MANUEL: "Otomatik oluşturma yok (elle)",
};

/** Fatura kaydına yazılan dönem metni. */
export const BILLING_PERIOD_INVOICE_LABEL: Record<BillingPeriod, string> = {
  HAFTALIK: "Haftalık Ödeme",
  IKI_HAFTALIK: "İki Haftalık Ödeme",
  AYLIK: "Aylık Ödeme",
  IKI_AYLIK: "İki Aylık Ödeme",
  OZEL_GUN: "Dönemsel Ödeme",
  MANUEL: "Ödeme",
};

/** Yalnızca OZEL_GUN periyodu gün aralığı ister. */
export function needsIntervalDays(period: BillingPeriod): boolean {
  return period === "OZEL_GUN";
}

/** MANUEL seçiliyse sistem kendiliğinden fatura açmaz. */
export function isAutoGenerated(period: BillingPeriod): boolean {
  return period !== "MANUEL";
}

/**
 * Periyodun insan tarafından okunabilir özeti — panelde firma kartında gösterilir.
 * Örn. "İki haftada bir · 10.000 ₺" veya "Her 45 günde bir · 5.000 ₺".
 */
export function describeBilling(
  period: BillingPeriod,
  intervalDays: number | null | undefined
): string {
  if (period === "OZEL_GUN") {
    return intervalDays ? `Her ${intervalDays} günde bir` : "Özel gün aralığı (tanımsız)";
  }
  return BILLING_PERIOD_LABEL[period];
}

/** Ayın son gününü verir (2026-02 → 28). */
function lastDayOfMonth(year: number, monthIndex: number): number {
  return new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate();
}

/**
 * Verilen vade tarihine N ay ekler. Ay sonu taşmasını engeller: 31 Ocak'a bir ay
 * eklendiğinde 3 Mart değil, 28/29 Şubat döner. Düz `setUTCMonth` bunu yapamıyordu.
 */
function addMonthsClamped(base: Date, months: number): Date {
  const y = base.getUTCFullYear();
  const m = base.getUTCMonth();
  const d = base.getUTCDate();

  const targetMonthAbs = m + months;
  const targetYear = y + Math.floor(targetMonthAbs / 12);
  const targetMonth = ((targetMonthAbs % 12) + 12) % 12;

  const day = Math.min(d, lastDayOfMonth(targetYear, targetMonth));
  return new Date(Date.UTC(targetYear, targetMonth, day, 0, 0, 0, 0));
}

/** Verilen vade tarihine N gün ekler. */
function addDays(base: Date, days: number): Date {
  const next = new Date(base);
  next.setUTCDate(next.getUTCDate() + days);
  return next;
}

/**
 * Bir sonraki fatura vadesini hesaplar.
 * MANUEL periyotta (veya OZEL_GUN'de gün aralığı tanımsızsa) null döner —
 * çağıran taraf bu durumda otomatik fatura açmamalıdır.
 */
export function nextDueDate(
  base: Date,
  period: BillingPeriod,
  intervalDays?: number | null
): Date | null {
  switch (period) {
    case "HAFTALIK":
      return addDays(base, 7);
    case "IKI_HAFTALIK":
      return addDays(base, 14);
    case "AYLIK":
      return addMonthsClamped(base, 1);
    case "IKI_AYLIK":
      return addMonthsClamped(base, 2);
    case "OZEL_GUN":
      return intervalDays && intervalDays > 0 ? addDays(base, intervalDays) : null;
    case "MANUEL":
      return null;
  }
}
